In [1]:
import numpy as np

In [2]:
np.random.rand(3,2)

array([[0.06627399, 0.62993297],
       [0.99288564, 0.01858111],
       [0.9994731 , 0.14890263]])

In [3]:
np.random.rand(3,2)

array([[0.66784155, 0.01850119],
       [0.03222249, 0.17668835],
       [0.04187989, 0.91915591]])

In [4]:
np.random.randint(34,100)

74

In [5]:
np.random.randint(20,56,100)

array([22, 47, 50, 36, 26, 40, 30, 37, 35, 46, 43, 36, 49, 22, 47, 29, 30,
       51, 22, 35, 20, 47, 55, 43, 21, 36, 44, 33, 46, 43, 33, 28, 51, 26,
       35, 52, 38, 37, 40, 38, 46, 40, 50, 50, 46, 41, 34, 40, 49, 38, 29,
       30, 40, 30, 35, 30, 47, 24, 35, 52, 21, 44, 44, 42, 51, 53, 25, 21,
       23, 43, 43, 52, 49, 20, 29, 42, 21, 43, 31, 30, 29, 32, 47, 29, 20,
       34, 45, 42, 49, 27, 27, 38, 47, 25, 21, 23, 40, 44, 54, 30])

In [6]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
rand_array=np.random.randint(0,100,20)
rand_array

array([62, 42, 11, 42,  5, 98, 98, 42, 39,  7, 33, 48, 74, 11, 96, 53, 50,
       47, 89, 42])

In [11]:
sample_array.reshape(3,1)

ValueError: cannot reshape array of size 30 into shape (3,1)

In [12]:
rand_array.min()

5

In [13]:
rand_array.argmin()

4

In [14]:
sample_array.dtype()

TypeError: 'numpy.dtype[int32]' object is not callable

In [15]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
a=np.random.rand(2,3)
a

array([[0.01763291, 0.50739133, 0.53114872],
       [0.2141219 , 0.23927672, 0.5011306 ]])

In [18]:
a.T

array([[0.01763291, 0.2141219 ],
       [0.50739133, 0.23927672],
       [0.53114872, 0.5011306 ]])

In [19]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
sample_array[3]

13

In [21]:
sample_array[3:7]

array([13, 14, 15, 16])

In [22]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [23]:
sample_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [26]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [25]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [27]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [29]:
import numpy as np

In [31]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [32]:
sample_matrix[0][2]

1

In [33]:
sample_matrix[1,:]

array([24, 23, 21, 33])

In [34]:
sample_matrix[0]

array([50, 20,  1, 23])

In [36]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [40]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [41]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [42]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [43]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [44]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [45]:
np.max(sample_array)

19

In [46]:
np.min(sample_array)

1

In [47]:
np.std(sample_array)

5.477225575051661

In [48]:
np.var(sample_array)

30.0

In [49]:
np.mean(sample_array)

10.0

In [50]:
array=np.random.rand(3,4)
array

array([[0.6655319 , 0.1450921 , 0.0801351 , 0.58495973],
       [0.33331019, 0.48702906, 0.83070607, 0.5613423 ],
       [0.78770446, 0.97033021, 0.28406126, 0.30821061]])

In [51]:
np.round(array,decimals=4)

array([[0.6655, 0.1451, 0.0801, 0.585 ],
       [0.3333, 0.487 , 0.8307, 0.5613],
       [0.7877, 0.9703, 0.2841, 0.3082]])

In [52]:
np.argmax(sample_array)

18

In [53]:
np.argmin(sample_array)

0

In [54]:
import pandas as pd
import numpy as np

In [60]:
labels=['w','x','y','z']
sample_list=[100,200,300,400]
array=np.array([1,2,3,4])
dict={'w':10,'x':20,'y':30,'z':40}


In [62]:
pd.Series(data=sample_list)

0    100
1    200
2    300
3    400
dtype: int64

In [64]:
pd.Series(data=sample_list,index=labels)

w    100
x    200
y    300
z    400
dtype: int64

In [65]:
pd.Series(sample_list,labels)

w    100
x    200
y    300
z    400
dtype: int64

In [66]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

In [69]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [70]:
sports1['football']

2

In [75]:
sports2=pd.Series([10,3,12,3],index=['cricket','football','vollyball','golf'])
sports2

cricket      10
football      3
vollyball    12
golf          3
dtype: int64

In [76]:
sports1+sports2

basketball     NaN
cricket       11.0
football       5.0
golf           7.0
vollyball      NaN
dtype: float64

In [79]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.451650  0.183598  0.044591  0.665791  0.605938
B  0.002745  0.445672  0.132391  0.243870  0.547209
C  0.582283  0.805245  0.290525  0.099782  0.680900
D  0.826450  0.413913  0.783206  0.929585  0.864494
E  0.661769  0.821184  0.810812  0.781191  0.534401
F  0.772170  0.181033  0.960998  0.331430  0.429943
G  0.896268  0.339307  0.660634  0.188284  0.763744
H  0.475522  0.236774  0.020095  0.784788  0.470478

In [80]:
df1['score8']=df1['score3']+df1['score4']
df1

score1    score2    score3    score4    score5    score8
A  0.451650  0.183598  0.044591  0.665791  0.605938  0.710382
B  0.002745  0.445672  0.132391  0.243870  0.547209  0.376261
C  0.582283  0.805245  0.290525  0.099782  0.680900  0.390307
D  0.826450  0.413913  0.783206  0.929585  0.864494  1.712791
E  0.661769  0.821184  0.810812  0.781191  0.534401  1.592003
F  0.772170  0.181033  0.960998  0.331430  0.429943  1.292428
G  0.896268  0.339307  0.660634  0.188284  0.763744  0.848919
H  0.475522  0.236774  0.020095  0.784788  0.470478  0.804883

In [82]:
df2={'ID':['101','102',103],'Name':['Akshay','sushant','Nikhil'],'Profit':['30','40','50']}
df=pd.DataFrame(df2)
df

ID     Name Profit
0  101   Akshay     30
1  102  sushant     40
2  103   Nikhil     50

In [83]:
df["ID"]

0    101
1    102
2    103
Name: ID, dtype: object

In [84]:
df[["ID","Name"]]

ID     Name
0  101   Akshay
1  102  sushant
2  103   Nikhil

In [86]:
df.drop("ID",axis=1)

Name Profit
0   Akshay     30
1  sushant     40
2   Nikhil     50

In [87]:
df.drop(2)

ID     Name Profit
0  101   Akshay     30
1  102  sushant     40

In [95]:
df=pd.read_csv("https://media.githubusercontent.com/media/datablist/sample-csv-files/main/files/organizations/organizations-100.csv")

In [96]:
df.head(10)

Index  Organization Id                     Name  \
0      1  FAB0d41d5b5d22c              Ferrell LLC   
1      2  6A7EdDEA9FaDC52  Mckinney, Riley and Day   
2      3  0bFED1ADAE4bcC1               Hester Ltd   
3      4  2bFC1Be8a4ce42f           Holder-Sellers   
4      5  9eE8A6a4Eb96C24              Mayer Group   
5      6  cC757116fe1C085           Henry-Thompson   
6      7  219233e8aFF1BC3           Hansen-Everett   
7      8  ccc93DCF81a31CD            Mcintosh-Mora   
8      9  0B4F93aA06ED03e                 Carr Inc   
9     10  738b5aDe6B1C6A5               Gaines Inc   

                          Website                            Country  \
0              https://price.net/                   Papua New Guinea   
1  http://www.hall-buchanan.info/                            Finland   
2       http://sullivan-reed.com/                              China   
3             https://becker.com/                       Turkmenistan   
4          http://www.brewer.com/                          Mauritius   
5               http://morse.net/                            Bahamas   
6           https://www.kidd.org/                           Pakistan   
7         https://www.brooks.com/  Heard Island and McDonald Islands   
8                http://ross.com/                             Kuwait   
9     http://sandoval-hooper.com/                         Uzbekistan   

                                      Description  Founded  \
0             Horizontal empowering knowledgebase     1990   
1             User-centric system-worthy leverage     2015   
2                  Switchable scalable moratorium     1971   
3  De-engineered systemic artificial intelligence     2004   
4              Synchronized needs-based challenge     1991   
5    Face-to-face well-modulated customer loyalty     1992   
6          Seamless disintermediate collaboration     2018   
7        Centralized attitude-oriented capability     1970   
8          Distributed impactful customer loyalty     1996   
9                 Multi-lateral scalable protocol     1997   

                        Industry  Number of employees  
0                       Plastics                 3498  
1    Glass / Ceramics / Concrete                 4952  
2                  Public Safety                 5287  
3                     Automotive                  921  
4                 Transportation                 7870  
5  Primary / Secondary Education                 4914  
6            Publishing Industry                 7832  
7                Import / Export                 4389  
8                       Plastics                 8167  
9       Outsourcing / Offshoring                 9698

In [97]:
df.tail(10)

Index  Organization Id                            Name  \
90     91  7ABc3c7ecA03B34                Sampson-Griffith   
91     92  4e0719FBE38e0aB                 Miles-Dominguez   
92     93  dEbDAAeDfaed00A                   Rowe and Sons   
93     94  61BDeCfeFD0cEF5  Valenzuela, Holmes and Rowland   
94     95  4e91eD25f486110          Best, Wade and Shepard   
95     96  0a0bfFbBbB8eC7c                    Holmes Group   
96     97  BA6Cd9Dae2Efd62                        Good Ltd   
97     98  E7df80C60Abd7f9               Clements-Espinoza   
98     99  AFc285dbE2fEd24                      Mendez Inc   
99    100  e9eB5A60Cef8354                  Watkins-Kaiser   

                     Website                      Country  \
90     http://hendricks.org/                        Benin   
91    http://www.turner.com/                    Gibraltar   
92  https://www.simpson.org/                  El Salvador   
93   https://www.dorsey.net/                       Taiwan   
94    https://zimmerman.com/                     Zimbabwe   
95     https://mcdowell.org/                     Ethiopia   
96         http://duffy.com/                     Anguilla   
97   http://www.flowers.net/  Falkland Islands (Malvinas)   
98    https://www.burke.net/              Kyrgyz Republic   
99   http://www.herring.com/                         Togo   

                                Description  Founded  \
90         Multi-layered composite paradigm     1972   
91            Organized empowering forecast     1996   
92        Balanced multimedia knowledgebase     1978   
93          Persistent tertiary focus group     1999   
94         Innovative background definition     1991   
95   Right-sized zero tolerance focus group     1975   
96  Reverse-engineered composite moratorium     1971   
97                  Progressive modular hub     1991   
98          User-friendly exuding migration     1993   
99            Synergistic background access     2009   

                       Industry  Number of employees  
90                     Textiles                 3881  
91  Civic / Social Organization                  897  
92          Facilities Services                 8172  
93               Transportation                 1483  
94           Gambling / Casinos                 4873  
95                  Photography                 2988  
96            Consumer Services                 4292  
97              Broadcast Media                  236  
98         Education Management                  339  
99           Financial Services                 2785

In [98]:
df.sample()

Index  Organization Id            Name                Website   Country  \
6      7  219233e8aFF1BC3  Hansen-Everett  https://www.kidd.org/  Pakistan   

                              Description  Founded             Industry  \
6  Seamless disintermediate collaboration     2018  Publishing Industry   

   Number of employees  
6                 7832

In [99]:
df.shape

(100, 9)

In [100]:
df.dtypes

Index                   int64
Organization Id        object
Name                   object
Website                object
Country                object
Description            object
Founded                 int64
Industry               object
Number of employees     int64
dtype: object

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Index                100 non-null    int64 
 1   Organization Id      100 non-null    object
 2   Name                 100 non-null    object
 3   Website              100 non-null    object
 4   Country              100 non-null    object
 5   Description          100 non-null    object
 6   Founded              100 non-null    int64 
 7   Industry             100 non-null    object
 8   Number of employees  100 non-null    int64 
dtypes: int64(3), object(6)
memory usage: 7.2+ KB


In [103]:
df.isnull().sum()

Index                  0
Organization Id        0
Name                   0
Website                0
Country                0
Description            0
Founded                0
Industry               0
Number of employees    0
dtype: int64

In [104]:
df.describe()

Index      Founded  Number of employees
count  100.000000   100.000000           100.000000
mean    50.500000  1995.410000          4964.860000
std     29.011492    15.744228          2850.859799
min      1.000000  1970.000000           236.000000
25%     25.750000  1983.500000          2741.250000
50%     50.500000  1995.000000          4941.500000
75%     75.250000  2010.250000          7558.000000
max    100.000000  2021.000000          9995.000000